# DadMadLib.py
adj1 = input("Please enter an adjective: ")
adj2 = input("Please enter an adjective: ")
nouna = input("Please enter a noun: ")
verbing = input("Please enter a verb ending in -ing: ")
nounb = input("Please enter a noun: ")
adj3 = input("Please enter an adjective: ")
noun1 = input("Please enter a noun: ")
adj4 = input("Please enter an adjective: ")
nounc = input("Please enter a noun: ")
noun2 = input("Please enter a noun: ")
verbing2 = input("Please enter a verb ending in -ing: ")
nounp = input("Please enter a plural noun: ")
verb1 = input("Please enter a verb: ")
nound = input("Please enter a noun: ")
adj5 = input("Please enter an adjective: ")
adv = input("Please enter an adverb: ")
verbed = input("Please enter a verb ending in -ed: ")
verbed2 = input("Please enter a past-tense verb: ")
noune = input("Please enter a noun: ")
noun3 = input("Please enter a noun: ")
print("Your MadLib:")
print("One", adj1, "day,", adj2, nouna, "was", verbing, "down a long", nounb, "in the middle of a", adj3, noun1,".")
print("At the end of the", nounb,", the", nouna, "found a", adj4, nounc, "stuck in a", noun2,".")
print('"',verbing2, nounp,'!" exclaimed', nouna,'. "We need to"', verb1, 'you a', nound, 'or you will be,', adj5,'!')
print(adv,',', nouna, verbed, 'a', noune, 'and', verbed2, 'it to', nounc,'.')
print(nounc, 'yelled, "But I really need a', noun3,'!')

