# DahliaMadLib.py
noun = input("Please enter a noun: ")
person = input("Please enter a kind of person: ")
ingverb = input("Please enter a verb ending in -ing: ")
exclamation = input("Please enter a exclamation: ")
noun2 = input("Please enter a noun: ")
color = input("Please enter a color: ")
person2 = input("Please enter a kind of person: ")
person3 = input("Please enter he or she (capitalized): ")
exclamation2 = input("Please enter a exclamation: ")
pverb = input("Please enter a past-tense verb: ")
feeling = input("Please enter a feeling: ")
print("Your MadLib:")
print("In a deep, dark, scary", noun, "a young", person, "was", ingverb, "down the street.")
print('Suddenly, "', exclamation, '!" he shouted! Meanwhile, hiding unnoticed in the', noun2, 'a man dressed in', color, 'was watching through binoculars.')
print('Dun, DUN, DUNNNNNNNNNN!')
print('The young', person2, 'whipped around!', person3, 'had sensed something unnoticed! "You!!!" the man shouted.')
print('The young person pulled out a ... SWORD!')
print('"', exclamation2, ', the man yelled! He', pverb, 'away!')
print('"Welp," the young person said. "I guess he\'s taken care of!"')
print('And so the young person lived', feeling, 'ly ever after.')

